 #  _   _       _   _           _____             
 # | \ | |     | | (_)         |  __ \            
 # |  \| | __ _| |_ ___   _____| |  | | _____   __
 # | . ` |/ _` | __| \ \ / / _ \ |  | |/ _ \ \ / /
 # | |\  | (_| | |_| |\ V /  __/ |__| |  __/\ V / 
 # |_| \_|\__,_|\__|_| \_/ \___|_____/ \___| \_/  
 #
 # Больше плагинов в https://vk.com/native_dev
 # По вопросам native.dev@mail.ru

regmenu-title: §aРегистрация
regmenu-text1: §aЗарегистрируйтесь, чтобы играть на нашем сервере.  §8Оставьте поле пустым, чтобы покинуть сервер.
regmenu-text2: Пароль
regmenu-passwd-field: §7Пароль...
regmenu-empty-passwd-field: Вы не хотели зарегистрироваться.

logmenu-title: Войти
logmenu-text1: §aВойдите, чтобы играть на нашем сервере.  §8Оставьте поле пустым, чтобы покинуть сервер.
logmenu-text2:  Пароль
logmenu-passwd-field: §7Пароль...
logmenu-empty-passwd-field: Вы не хотели входить в систему.